version: '2'

services:
  sequelize:
    build: .
    links:
     - mysql-57
    volumes:
      - .:/sequelize
    environment:
      SEQ_DB: sequelize_test
      SEQ_USER: sequelize_test
      SEQ_PW: sequelize_test

  # MySQL
  mysql-57:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sequelize_test
      MYSQL_USER: sequelize_test
      MYSQL_PASSWORD: sequelize_test
    volumes:
      - /mnt/sequelize-mysql-ramdisk:/var/lib/mysql
    ports:
      - "8999:3306"
    container_name: mysql-57